travis:
  secure:
    BINSTAR_TOKEN: uaWvbMIk9KPDE6PTQpOU2VfL3DvUdKepNk7k+CwCPvfCjlfwJ1y2yIv4bb2lmwpKHPE7S3nSv7ffEm8lNju+cWJB1C8YmEtiqsAWEFoMMC0/+P346h9iQrDyXZVyhKj3dSbGbKdQdfHDg89bFJuxgfyGoYaN6ySKGg/lgQt4m+tXFS3XSaI3CXgquH35p7+d0EJihCSaNz8oesNYqOdmGG7SAPYi+0VqnyZ1pdBENaZqyTBJd8nrZhHZkjoVlfTMduzHqf4C9sCTEvdA1AeaX5xhwXo2U3DWw2ko/uitOIGgd9VquCx9xIsBUXg8rSbggaaUuftqPxJQDowTPvfEO3wN18ngis+XZnWuuXFCLf4tEZ2rM1BpR2w6+5vx2roHRGpGJkah0dWRf7ZwS9WHN56HZqmXezAYhLK9tHdaT1JHkjeWlCImh5aWJqJFjGplJV7sP3BtA4Gxk4IqXOUJFybZUiQA3r9wsN2t00KCiyTf62DWD1HgODEKLH6UMNjCKUv+DXcebfBiGs4gG+kCz/KSvX8n6Ji1JBLM7/Wi/BYb2sg/58DcyS1pCB11MynliglRbm9xqPxCC/pmTHDuknwuPnCaoophcSmM31yTJUs8NERHsghBuSwodF7UCvkIxFAHmdDfoaVrY9gSSkTMDXjQ2A29f6OflSY4zazdbNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
